server.port=8080
spring.application.name=pg-veterinaria

spring.datasource.url=jdbc:postgresql://ep-morning-truth-apbuunqe-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uNyf7p2aGrHl
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true